library(shiny)
library(data.table)
library(dplyr)
library(tidyr)
library(ggplot2)
library(googleVis)
library(leaflet)
library(ggmap)
nyct2010<-read.csv('nyct2010.csv')
data<-read.csv('data2.csv')
data2<-read.csv('data2.csv')
weatherdata<-read.csv('weather.csv')
weatherlist = list('all','sunny/cloudy'='sunny','rain','snow')
factorlist=list('all','Distraction'='Driver Inattention/Distraction','Other Vehicular'='Other Vehicular','Failure to Yield Right-of-Way','Turning Improperly','Tired'='Fatigued/Drowsy','Backing Unsafely','Lost Consciousness','Following Too Closely','Unsafe Lane Changing','Passing or Lane Usage Improper','Driver Inexperience','Alcohol'='Alcohol Involvement')
typelist=list('PASSENGER VEHICLE','SUV'='SPORT UTILITY / STATION WAGON','TAXI','TRACK'='PICK-UP TRUCK','VAN','LIVERY VEHICLE','SMALL COM'='SMALL COM VEH(4 TIRES)','BUS','BICYCLE','MOTORCYCLE')


